import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
const JotaiProvider = dynamic(() => import("@/providers/jotaiProvider"), { ssr: false });
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Introduction",
  description: "Generated by BJR",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-br from-slate-800 to-slate-950 h-screen`}>
        <JotaiProvider>
          <div className="px-20">
            {children}
          </div>
        </JotaiProvider>
      </body>
    </html>
  );
}
